// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ad_info_account_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountRouterClient is the client API for AccountRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountRouterClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type accountRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountRouterClient(cc grpc.ClientConnInterface) AccountRouterClient {
	return &accountRouterClient{cc}
}

func (c *accountRouterClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/AccountRouter/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountRouterClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/AccountRouter/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountRouterServer is the server API for AccountRouter service.
// All implementations must embed UnimplementedAccountRouterServer
// for forward compatibility
type AccountRouterServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Register(context.Context, *RegisterRequest) (*LoginResponse, error)
	mustEmbedUnimplementedAccountRouterServer()
}

// UnimplementedAccountRouterServer must be embedded to have forward compatible implementations.
type UnimplementedAccountRouterServer struct {
}

func (UnimplementedAccountRouterServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountRouterServer) Register(context.Context, *RegisterRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAccountRouterServer) mustEmbedUnimplementedAccountRouterServer() {}

// UnsafeAccountRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountRouterServer will
// result in compilation errors.
type UnsafeAccountRouterServer interface {
	mustEmbedUnimplementedAccountRouterServer()
}

func RegisterAccountRouterServer(s grpc.ServiceRegistrar, srv AccountRouterServer) {
	s.RegisterService(&AccountRouter_ServiceDesc, srv)
}

func _AccountRouter_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRouterServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRouter/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRouterServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountRouter_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountRouterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountRouter/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountRouterServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountRouter_ServiceDesc is the grpc.ServiceDesc for AccountRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AccountRouter",
	HandlerType: (*AccountRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountRouter_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AccountRouter_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ad_info_account_rpc.proto",
}
